let parameter = [
    'demam',
    'mual',
    'pusing',
    'lemah',
    'nyeri',
    'diare',
    'muntah',
    'batuk',
    'sesak nafas',
    'sakit kepala',
    'sakit tenggorokan',
    'hidung tersumbat',
    'sakit perut',
    'sakit pinggang',
    'perut kembung',
    'nyeri sendi',
    'ruam',
    'kejang',
    'gatal',
    'berdarah',
    'mata merah',
    'kaki bengkak',
    'susah tidur',
    'sering buang air kecil',
    'nyeri dada',
    'penurunan berat badan',
    'kelelahan',
    'sariawan',
    'kulit kering',
    'kulit bersisik',
    'kulit kemerahan',
    'keputihan',
    'disfungsi ereksi',
    'perubahan suasana hati',
    'stres',
    'cemas',
    'depresi',
    'gangguan tidur',
    'gangguan makan',
    'kecemasan sosial',
    'fobia',
    'obsesi',
    'trauma',
    //harga
    'murah',
    'mahal',
    //rating
    'produk',
    'rating',
    'bagus',
    'tinggi',
    'pilih',
    'barang',
    'penilaian',
    'terbaik',
    'favorit',
    'kualitas',
    'pengguna',
    'positif',
    'populer',
    'bintang lima',
    'paling baik',
  ];

export default parameter;